display-controller: Improve makefile

diff --git a/display-controller/Makefile b/display-controller/Makefile
--- a/display-controller/Makefile
+++ b/display-controller/Makefile
@@ -1,23 +1,35 @@
 
-BASEPROGS=/home/nathan/fpga-ice40
-YOSYS=$(BASEPROGS)/yosys/yosys
-ARACHNEPNR=$(BASEPROGS)/arachne-pnr/bin/arachne-pnr
-ICEPACK=$(BASEPROGS)/icestorm/icepack/icepack
-IVERILOG=iverilog
-VVP=vvp
+# output
+Q = @
+QSH = > /dev/null 2>&1
+
+BASEPROGS = /home/nathan/fpga-ice40
+YOSYS = $(BASEPROGS)/yosys/yosys
+ARACHNEPNR = $(BASEPROGS)/arachne-pnr/bin/arachne-pnr
+ICEPACK = $(BASEPROGS)/icestorm/icepack/icepack
+IVERILOG = iverilog
+VVP = vvp
+
 
 all: bitstream tests
 
-tests: $(patsubst tests/%.v,obj/tests/%.vvp,$(shell ls tests/test-*.v))
+BROKEN = test-display-driver-simple
+TESTS = $(patsubst tests/%.v,%,$(shell ls tests/test-*.v))
+RUNTESTS = $(filter-out $(BROKEN),$(patsubst tests/%.v,%,$(TESTS)))
 
-bitstream: obj/top.bin
+tests: $(RUNTESTS)
+
+$(foreach t,$(TESTS),$(eval $t: obj/tests/$t_run))
+
+bitstream: obj/top.bin obj/top.asc
 
 clean:
-	-rm *.vcd
-	-rm -rf obj/
-	-rm -rf obj/tests/
+	@echo "[CLEAN] cleaning..."
+	$(Q)-rm *.vcd
+	$(Q)-rm -rf obj/
+	$(Q)-rm -rf obj/tests/
 
-.PHONY: all clean tests bitstream
+.PHONY: all clean tests bitstream $(TESTS)
 
 #
 # Tests
@@ -29,10 +41,18 @@ obj/tests/test-display-color-encoder-simple.vvp: display-color-encoder.v
 obj/tests/test-spi-slave-simple.vvp: spi-slave.v
 obj/tests/test-top.vvp: top.v display-memory.v display-driver.v display-color-encoder.v spi-slave.v
 
-obj/tests/test-%.vvp: tests/test-%.v tests/helpers.v
-	-mkdir -p obj/tests
-	$(IVERILOG) -o $@ $^
-	$(VVP) $@ -lxt2
+obj/tests/%.vvp: tests/%.v tests/helpers.v
+	$(Q)-mkdir -p obj/tests
+	@echo "[SIMUL] $(patsubst obj/tests/%.vvp,%,$@)"
+	$(Q)$(IVERILOG) -o $@ $^ $(QSH)
+
+obj/tests/%_run: obj/tests/%.vvp
+	@echo "[TEST ] $(patsubst obj/tests/%_run,%,$@)...";
+	$(Q)if ! $(VVP) -n $^ -lxt2 $(QSH); then \
+			echo "        $(patsubst obj/tests/%_run,%,$@)... Failed"; \
+		else \
+			echo "        $(patsubst obj/tests/%_run,%,$@)... Passed"; \
+		fi
 
 #
 # Bistream/Synth/etc.
@@ -42,14 +62,17 @@ obj/top.blif: display-memory.v display-driver.v display-color-encoder.v spi-slav
 
 # synth, pnr, bitmap
 obj/%.blif: %.v
-	-mkdir -p $$(dirname $@)
-	$(YOSYS) -p "synth_ice40 -top $$(basename $@ .blif | sed s/-/_/) -blif $@" $^
+	$(Q)-mkdir -p $$(dirname $@)
+	@echo "[SYNTH] $@"
+	$(Q)$(YOSYS) -p "synth_ice40 -top $$(basename $@ .blif | sed s/-/_/) -blif $@" $^ $(QSH)
 
 obj/%.asc: obj/%.blif %.pcf
-	-mkdir -p $$(dirname $@)
-	$(ARACHNEPNR) -d 1k -P tq144 -o $@ -p $(firstword $(filter %.pcf,$^)) $(firstword $(filter %.blif,$^))
+	$(Q)-mkdir -p $$(dirname $@)
+	@echo "[P-N-R] $@"
+	$(Q)$(ARACHNEPNR) -d 1k -P tq144 -o $@ -p $(firstword $(filter %.pcf,$^)) $(firstword $(filter %.blif,$^)) $(QSH)
 
 obj/%.bin: obj/%.asc
-	-mkdir -p $$(dirname $@)
-	$(ICEPACK) $^ $@
+	$(Q)-mkdir -p $$(dirname $@)
+	@echo "[BMAP ] $@"
+	$(Q)$(ICEPACK) $^ $@ $(QSH)
 
