display-controller/Makefile: Make it better
Using $(call ...) for actual commands doesn't work nicely, so use it
differently.

diff --git a/display-controller/Makefile b/display-controller/Makefile
--- a/display-controller/Makefile
+++ b/display-controller/Makefile
@@ -3,30 +3,17 @@
 Q = $(if $(filter $(V),2),,@)
 QSH = $(if $(V),,> /dev/null 2>&1)
 
-# cmd runner
-cmd-pf-call = @ \
-	mkdir -p $(dir $@); \
-	if ! $(1) > $@.log 2>&1; then \
-		cat $@.log $(QSH); \
-		printf " %-6s  `tput setaf 1`%4s`tput sgr0`  %s\n" "$(2)" "fail" "$(3)"; \
-	else \
-		cat $@.log $(QSH); \
-		printf " %-6s  `tput setaf 2`%4s`tput sgr0`  %s\n" "$(2)" "pass" "$(3)"; \
-	fi; \
-	rm $@.log
+safe-dir = @mkdir -p $(dir $@)
+echo-info = @printf " %-6s  %4s  %s\n" "$(1)" "" "$(2)"; \
 
-cmd-call = @ \
-	mkdir -p $(dir $@); \
-	printf " %-6s  %4s  %s\n" "$(2)" "" "$(3)"; \
-	if ! $(1) > $@.log 2>&1; then \
-		cat $@.log $(QSH); \
-		printf " %-6s  `tput setaf 1`%4s`tput sgr0`  %s\n" "$(2)" "fail" "$(3)"; \
-	fi; \
-	rm $@.log
-
-cmd-null = @ \
-	mkdir -p $(dir $@); \
-	printf " %-6s  %4s  %s\n" "$(1)" "" "$(2)"
+echo-pass = printf " %-6s  `tput setaf 2`%4s`tput sgr0`  %s\n" "$(1)" "pass" "$(2)"
+echo-fail = printf " %-6s  `tput setaf 1`%4s`tput sgr0`  %s\n" "$(1)" "fail" "$(2)"
+echo-pf-check = ; STATUS=$$?; \
+		if [ "$$STATUS" = "0" ]; then \
+			$(call echo-pass,$(1),$(2)); \
+		else \
+			$(call echo-fail,$(1),$(2)); \
+		fi
 
 BASEPROGS = /home/nathan/fpga-ice40
 YOSYS = $(BASEPROGS)/yosys/yosys
@@ -60,8 +47,9 @@ display-driver.v: display-color-encoder.v
 top.v: display-driver.v display-memory.v spi-controller.v
 
 obj/gamma-lookup-table.hex: scripts/gamma-correction-tables.py
-	$(call cmd-null,MEM,generating gamma correction table)
-	@./scripts/gamma-correction-tables.py > $@
+	$(call safe-dir)
+	$(call echo-info,MEM,generating gamma correction table)
+	$(Q)./scripts/gamma-correction-tables.py > $@
 
 #
 # Tests
@@ -73,14 +61,20 @@ obj/tests/test-display-memory-simple.vvp: display-memory.v
 obj/tests/test-display-color-encoder-simple.vvp: display-color-encoder.v
 obj/tests/test-spi-slave-simple.vvp: spi-slave.v
 obj/tests/test-spi-controller.vvp: spi-controller.v spi-slave.v
+obj/tests/test-spi-controller-segments.vvp: spi-controller.v spi-slave.v
 obj/tests/test-top.vvp: top.v display-memory.v display-driver.v display-color-encoder.v spi-controller.v spi-slave.v
 obj/tests/test-top-load-spi.vvp: top.v display-memory.v display-driver.v display-color-encoder.v spi-controller.v spi-slave.v
 
 obj/tests/%.vvp: tests/%.v tests/helpers.v
-	$(call cmd-call,$(IVERILOG) -D SIMULATION -g2012 -o $@ $(filter-out tests/helpers.v,$^),SIM,$(patsubst obj/tests/%.vvp,%,$@))
+	$(call safe-dir)
+	$(call echo-info,SIM,$(patsubst obj/tests/%.vvp,%,$@))
+	$(Q)$(IVERILOG) -D SIMULATION -g2012 -o $@ $(filter-out tests/helpers.v,$^)
 
+obj/tests/%_run: INFO_NAME = TEST
 obj/tests/%_run: obj/tests/%.vvp
-	$(call cmd-pf-call,$(VVP) -n $^ -lxt2,TEST,$(patsubst obj/tests/%_run,%,$@))
+	$(call safe-dir)
+	$(call echo-info,$(INFO_NAME),$(patsubst obj/tests/%_run,%,$@))
+	$(Q)$(VVP) -n $^ -lxt2 $(QSH) $(call echo-pf-check,$(INFO_NAME),$(patsubst obj/tests/%_run,%,$@))
 
 #
 # Bistream/Synth/etc.
@@ -90,12 +84,19 @@ obj/top.blif: display-memory.v display-driver.v display-color-encoder.v spi-cont
 
 # synth, pnr, bitmap
 obj/%.blif: %.v
-	$(call cmd-call,$(YOSYS) -p "$(foreach f,$(filter %.v,$^),read_verilog -defer -DSYNTHESIS $f; ) synth_ice40 -top $$(basename $@ .blif | sed s/-/_/) -blif $@",SYNTH,$@)
+	$(call safe-dir)
+	$(call echo-info,SYNTH,$@)
+	$(Q)$(YOSYS) -p "$(foreach f,$(filter %.v,$^),read_verilog -defer -DSYNTHESIS $f; ) synth_ice40 -top $$(basename $@ .blif | sed s/-/_/) -blif $@" $(QSH)
 
 obj/%.asc: obj/%.blif %.pcf
-	$(call cmd-call,$(ARACHNEPNR) -d 1k -P tq144 -o $@ -p $(firstword $(filter %.pcf,$^)) $(firstword $(filter %.blif,$^)),P-N-R,$@)
-	$(call cmd-pf-call,$(ICETIME) -C $(ICEBOX)/chipdb-1k.txt -d hx1k -P tq144 -p $(firstword $(filter %.pcf,$^)) -c 12 $@,TIMING,$@)
+	$(call safe-dir)
+	$(call echo-info,P-N-R,$@)
+	$(Q)$(ARACHNEPNR) -d 1k -P tq144 -o $@ -p $(firstword $(filter %.pcf,$^)) $(firstword $(filter %.blif,$^)) $(QSH)
+	$(call echo-info,TIMING,$@)
+	$(Q)$(ICETIME) -C $(ICEBOX)/chipdb-1k.txt -d hx1k -P tq144 -p $(firstword $(filter %.pcf,$^)) -c 12 $@ $(QSH)
 
 obj/%.bin: obj/%.asc
-	$(call cmd-call,$(ICEPACK) $^ $@,BITMAP,$@)
+	$(call safe-dir)
+	$(call echo-info,BITMAP,$@)
+	$(Q)$(ICEPACK) $^ $@ $(QSH)
 
