display-controller/Makefile: Rework for nextpnr, boards and more
- Handle being able to build using nextpnr or arachne-pnr.
- Add the board_* top level
- Allow for mixed configuration at the bitstream level (device/package)
- Clean up reporting and handle failed exit to dump the log

diff --git a/display-controller/Makefile b/display-controller/Makefile
--- a/display-controller/Makefile
+++ b/display-controller/Makefile
@@ -9,18 +9,15 @@ has-command = $(if $(shell command -v $(1) 2> /dev/null),$(shell command -v $(1)
 has-directory = $(if $(shell test -d $(1) && echo $(1)),$(1),$(2))
 
 safe-dir = @mkdir -p $(dir $@)
-echo-info = @printf " %-6s  %4s  %s\n" "$(1)" "" "$(2)"; \
+echo-info = @printf " %-12s  %4s  %s\n" "$(1)" "" "$(2)"; \
 
-echo-pass = printf " %-6s  $(call tput,setaf 2)%4s$(call tput,sgr0)  %s\n" "$(1)" "pass" "$(2)"
-echo-fail = printf " %-6s  $(call tput,setaf 1)%4s$(call tput,sgr0)  %s\n" "$(1)" "fail" "$(2)"
-echo-pf-check = ; STATUS=$$?; \
-		if [ "$$STATUS" = "0" ]; then \
-			$(call echo-pass,$(1),$(2)); \
-		else \
-			$(call echo-fail,$(1),$(2)); \
-		fi
+echo-pass = printf " %-12s  $(call tput,setaf 2)%4s$(call tput,sgr0)  %s\n" "$(1)" "pass" "$(2)"
+echo-fail = printf " %-12s  $(call tput,setaf 1)%4s$(call tput,sgr0)  %s\n" "$(1)" "fail" "$(2)"
 echo-report = @sh -c "echo '-------------------- $(1) --------------------'; cat $(2); echo '-------------------- $(1) --------------------'"
 echo-report-test-assert = @sh -c "echo '-------------------- $(1) --------------------'; cat $(2) $(if $(filter $(V),2),,| egrep assertion\|info); echo '-------------------- $(1) --------------------'"
+
+echo-pf-check = ; if [ $$? = 0 ]; then $(call echo-pass,$(1),$(2)); else $(call echo-fail,$(1),$(2)); fi
+log-report = > $(1) 2>&1; if [ $$? != 0 ]; then cat $(1); exit $$?; fi
 
 # define variables for commands
 IVL_PATH ?= $(abspath $(dir $(realpath $(call has-command,iverilog)))/../lib/ivl)
@@ -28,10 +25,10 @@ IVERILOG ?= $(call has-command,iverilog) -B$(IVL_PATH)
 VVP ?= $(call has-command,vvp) -M$(IVL_PATH)
 YOSYS ?= $(call has-command,yosys)
 ARACHNEPNR ?= $(call has-command,arachne-pnr)
+NEXTPNR ?= $(call has-command,nextpnr-ice40)
 ICEPACK ?= $(call has-command,icepack)
 ICETIME ?= $(call has-command,icetime)
 ICEPLL ?= $(call has-command,icepll)
-ICEBOX ?= $(abspath $(dir $(realpath $(call has-command,icepack)))/../share/icebox)
 
 # output dir
 O ?= $(shell realpath obj)
@@ -40,17 +37,28 @@ S ?= $(shell realpath .)
 VPATH = $(S)
 
 # common targets
-all: bitstream tests
+all: bitstream-icestick bitstream-up5k
+
+# frequencies for the top level design (in MHz)
+TARGET_FREQ = 24
 
 # bitstream and dependencies
-bit: bitstream
-bitstream: $(O)/top.bin $(O)/top.asc $(O)/top.asc.timing.log
-$(O)/top.blif: top.v \
-		display_driver.v display_memory.v \
-		data_loader.v \
-		spi_controller.v spi_slave.v \
-		uart/uart_rx.v uart/uart_tx.v \
-		$(O)/top_pll_config.v $(O)/gamma_lookup_table_10.hex
+bitstream-icestick: $(O)/board_icestick.bin
+$(O)/board_icestick.bin: SOURCE_FREQ = 12
+$(O)/board_icestick.bin: TARGET_DEVICE = hx1k
+$(O)/board_icestick.bin: TARGET_PACKAGE = tq144
+$(O)/board_icestick.bin: $(O)/board_icestick.nextpnr.asc
+$(O)/board_icestick.blif $(O)/board_icestick.yosys.json: board_icestick.v $(O)/board_icestick_pll_config.v *.v
+
+bitstream-up5k: $(O)/board_up5k.bin
+$(O)/board_up5k.bin: SOURCE_FREQ = 12
+$(O)/board_up5k.bin: TARGET_DEVICE = up5k
+$(O)/board_up5k.bin: TARGET_PACKAGE = sg48
+$(O)/board_up5k.bin: $(O)/board_up5k.nextpnr.asc
+$(O)/board_up5k.blif $(O)/board_up5k.yosys.json: board_up5k.v $(O)/board_up5k_pll_config.v *.v
+
+# gamma dep
+display_color_encoder.v: $(O)/gamma_lookup_table_10.hex
 
 # dependencies
 $(O)/tests/tests/display_color_encoder_10b.vvp: display_color_encoder.v $(O)/gamma_lookup_table_10.hex
@@ -135,61 +143,68 @@ $(O)/tests/%.run.log: $(O)/tests/%.vvp
 	$(Q)cd $(O) && $(VVP) -n $(abspath $^) -lxt2 > $(abspath $@) 2>&1 $(call echo-pf-check,TEST,$(TEST_NAME))
 	$(call echo-report-test-assert,$@,$@) $(QSH)
 
-# frequencies for the top level design (in MHz)
-SOURCE_FREQ = 12
-TARGET_FREQ = 24
-TARGET_DEVICE = 1k
-TARGET_DEVICE_VARIANT = hx
-TARGET_PACKAGE = tq144
-
 # pll source generation
 $(O)/%_pll_config.v:
 	$(call safe-dir)
 	$(call echo-info,PLL,$*)
-	$(Q)$(ICEPLL) -i $(SOURCE_FREQ) -o $(TARGET_FREQ) -m -f $@ > $@.log
-	$(call echo-report,PLL Configuration for $@,$@.log) $(QSH)
+	$(Q)$(ICEPLL) -i $(SOURCE_FREQ) -o $(TARGET_FREQ) -m -f $@ \
+		$(call log-report,$@.log)
 
 # synth, pnr, bitmap
-$(O)/%.blif: FLAGS = -DSYNTHESIS -DTARGET_FREQ=$(TARGET_FREQ)
-$(O)/%.blif:
+$(O)/%.blif $(O)/%.yosys.json: FLAGS = -DSYNTHESIS -DTARGET_FREQ=$(TARGET_FREQ)
+$(O)/%.blif $(O)/%.yosys.json:
 	$(call safe-dir)
 	$(call echo-info,SYNTH,$*)
-	$(Q)cd $(O) && $(YOSYS) \
-		-p "read_verilog -defer -I$(abspath $(O)) $(FLAGS) $(abspath $(filter %.v,$^)); \
-			synth_ice40 -top $(notdir $*) -blif $(abspath $@)" \
-			> $@.synthesis.log 2>&1
+	$(Q)cd $(O); $(YOSYS) \
+		-p " \
+			read_verilog -defer -I$(abspath $(O)) $(FLAGS) $(abspath $(filter %.v,$^)); \
+			synth_ice40 -top $(notdir $*) -json $(abspath $(O)/$*.yosys.json) -blif $(abspath $(O)/$*.blif); \
+		" $(call log-report,$@.synthesis.log)
 	$(Q)cat $@.synthesis.log | sed '/^[[:digit:]\.]* Printing.*$$/,/^[[:digit:]].*$$/{//!b};d'
 
-$(O)/%.asc: $(O)/%.blif %.pcf
+$(O)/%.arachne.asc: $(O)/%.blif %.pcf
 	$(call safe-dir)
-	$(call echo-info,P-N-R,$*)
+	$(call echo-info,PNR arachne,$*)
 	$(Q)$(ARACHNEPNR) \
-		-d $(TARGET_DEVICE) \
+		-d $(foreach d,384 1k 5k lm4k 8k,$(findstring $(d),$(TARGET_DEVICE))) \
 		-P $(TARGET_PACKAGE) \
 		-o $@ \
 		-p $(abspath $(firstword $(filter %.pcf,$^))) \
 		$(abspath $(firstword $(filter %.blif,$^))) \
-		> $@.log 2>&1
-	$(call echo-report,Place and Route report for $*,$@.log) $(QSH)
+		$(call log-report,$@.log)
 	$(Q)echo ""; echo "=== $* (packed) ==="; echo ""
 	$(Q)cat $@.log | sed '/^After packing:$$/,/^$$/{//!b};d'
 	$(Q)echo ""; echo "=== $* (placed) ==="; echo ""
 	$(Q)cat $@.log | sed '/^After placement:$$/,/^$$/{//!b};d'
 	$(Q)echo ""
-
-$(O)/%.asc.timing.log: $(O)/%.asc $(S)/%.pcf
-	$(call safe-dir)
-	$(call echo-info,TIMING,$*)
-	$(Q)$(ICETIME) \
-		-C $(ICEBOX)/chipdb-$(TARGET_DEVICE).txt \
-		-d $(TARGET_DEVICE_VARIANT)$(TARGET_DEVICE) \
+	$(Q)$(call log-report,$@.timing.log,$(ICETIME) \
+		-d $(TARGET_DEVICE) \
 		-P $(TARGET_PACKAGE) \
 		-p $(abspath $(firstword $(filter %.pcf,$^))) \
-		-c $(TARGET_FREQ) $(abspath $(firstword $(filter %.asc,$^))) \
-			> $@ 2>&1 $(call echo-pf-check,TIMING,$*)
-	$(call echo-report,Timing Report for $*,$@) $(QSH)
+		-c $(TARGET_FREQ) $@) \
+		$(call log-report,$@.log) \
+		$(call echo-pf-check,TIMING,$*)
 
-$(O)/%.bin: $(O)/%.asc
+$(O)/%.nextpnr.asc: $(O)/%.yosys.json %.pcf
+	$(call safe-dir)
+	$(call echo-info,PNR nextpnr,$*)
+	$(Q)$(NEXTPNR) \
+		--$(TARGET_DEVICE) \
+		--json $(abspath $(firstword $(filter %.yosys.json,$^))) \
+		--pcf $(abspath $(firstword $(filter %.pcf,$^))) \
+		--asc $@ \
+		$(call log-report,$@.log)
+	$(Q)echo ""; echo "=== $* ==="; echo ""
+	$(Q)cat $@.log | sed '/^Info: Device utilisation:$$/,/^$$/{//!b};d' | sed 's/^Info://'
+	$(Q)echo ""
+	$(Q)$(call log-report,$@.timing.log,$(ICETIME) \
+		-d $(TARGET_DEVICE) \
+		-P $(TARGET_PACKAGE) \
+		-p $(abspath $(firstword $(filter %.pcf,$^))) \
+		-c $(TARGET_FREQ) $@) \
+		$(call echo-pf-check,TIMING,$*)
+
+$(O)/%.bin:
 	$(call safe-dir)
 	$(call echo-info,BITMAP,$*)
 	$(Q)$(ICEPACK) $(abspath $(firstword $^)) $(abspath $@) $(QSH)
